apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: yaneisy/backend:django
        name: web
        ports:
        - containerPort: 8000
          name: web




